### ISSUE TITLE
After changes made to app as of 11/21- Broken post button

### ISSUE THREAD

**Issue by don1997** [don1997/csm#14]
# Front end issue
Post button isn't doing what it needs to do for snippet edit and new

**Comment by don1997** [comment]
# Finding
Issue is related to placement of 
<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='pygments.css') }}">
in templates

**Comment by don1997** [comment]
# Finding
Need to handle snippet.title and unique constraint. snippet.title must be unique across entire db. 
Need to handle snippet.title uniqueness scope

**Comment by don1997** [comment]
## Copy of error Log
IntegrityError

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: snippet.title
[SQL: INSERT INTO snippet (title, content, date_posted, user_id) VALUES (?, ?, ?, ?)]
[parameters: ('test', 'test', '2023-11-21 18:14:48.621552', 9)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context

    self.dialect.do_execute(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute

    cursor.execute(statement, parameters)

    The above exception was the direct cause of the following exception:
    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app

    response = self.handle_exception(e)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask_login/utils.py", line 277, in decorated_view

    return current_app.ensure_sync(func)(*args, **kwargs)

    File "/home/donald/Projects/csm/src/app/views.py", line 94, in new_snippet

    db.session.commit()

    File "<string>", line 2, in commit
    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1431, in commit

    self._transaction.commit(_to_root=self.future)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit

    self._prepare_impl()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl

    self.session.flush()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3363, in flush

    self._flush(objects)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3502, in _flush

    with util.safe_reraise():

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

    compat.raise_(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_

    raise exception

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush

    flush_context.execute()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute

    rec.execute(self)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute

    util.preloaded.orm_persistence.save_obj(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj

    _emit_insert_statements(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements

    result = connection._execute_20(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20

    return meth(self, args_10style, kwargs_10style, execution_options)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection

    return connection._execute_clauseelement(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement

    ret = self._execute_context(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context

    self._handle_dbapi_exception(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception

    util.raise_(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_

    raise exception

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context

    self.dialect.do_execute(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute

    cursor.execute(statement, parameters)

    sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: snippet.title
    [SQL: INSERT INTO snippet (title, content, date_posted, user_id) VALUES (?, ?, ?, ?)]
    [parameters: ('test', 'test', '2023-11-21 18:14:48.621552', 9)]
    (Background on this error at: https://sqlalche.me/e/14/gkpj)

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object
