### ISSUE TITLE
Db broke issue

### ISSUE THREAD

**Issue by don1997** [don1997/csm#24]
OperationalError

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.password AS user_password 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context

    self.dialect.do_execute(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute

    cursor.execute(statement, parameters)

    The above exception was the direct cause of the following exception:
    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app

    response = self.handle_exception(e)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

    File "/home/donald/Projects/csm/src/app/views.py", line 18, in home

    return render_template('home.html')

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template

    ctx.app.update_template_context(context)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask/app.py", line 756, in update_template_context

    context.update(func())

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask_login/utils.py", line 392, in _user_context_processor

    return dict(current_user=_get_user())

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask_login/utils.py", line 359, in _get_user

    current_app.login_manager._load_user()

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 355, in _load_user

    user = self._user_callback(user_id)

    File "/home/donald/Projects/csm/src/app/__init__.py", line 35, in load_user

    return User.query.get(int(user_id))

    File "<string>", line 2, in get
    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 401, in warned

    return fn(*args, **kwargs)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 943, in get

    return self._get_impl(ident, loading.load_on_pk_identity)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 947, in _get_impl

    return self.session._get_impl(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2892, in _get_impl

    return db_load_fn(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity

    session.execute(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1692, in execute

    result = conn._execute_20(statement, params or {}, execution_options)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20

    return meth(self, args_10style, kwargs_10style, execution_options)

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection

    return connection._execute_clauseelement(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement

    ret = self._execute_context(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context

    self._handle_dbapi_exception(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception

    util.raise_(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_

    raise exception

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context

    self.dialect.do_execute(

    File "/home/donald/Projects/csm/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute

    cursor.execute(statement, parameters)

    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
    [SQL: SELECT user.id AS user_id, user.username AS user_username, user.password AS user_password 
    FROM user 
    WHERE user.id = ?]
    [parameters: (1,)]
    (Background on this error at: https://sqlalche.me/e/14/e3q8)

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by don1997** [comment]
# Sol
Paste older version of db into it. Tables were deleted.

**Comment by don1997** [comment]
used db from branch :: commit 2369f376d71073f04c23f2669d2f8f0e8ccf46bf (HEAD -> v0.6.0_Bootstrap5, origin/v0.6.0_Bootstrap5)

**Comment by don1997** [comment]
# note
commit 3de59b9714aac63b26a29974f0381783b20004e3
AND
commit ad62e2eae9c8a8e520bf0b823577df55d0e6f99e (HEAD -> v0.6.0_Bootstrap5)

contain broken main db's. Use older db to fix

**Comment by don1997** [comment]
#   Make sure test_config is below the database.db 
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.config['SECRET_KEY'] = 'thisisasecretkey'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    if test_config:
        app.config.update(test_config)

# if 
 if test_config:
        app.config.update(test_config)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.config['SECRET_KEY'] = 'thisisasecretkey'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

Then test_db will overwrite database.db thus destroying database.db since test_db tears down.
